# Generated by Django 4.2.30 on 2026-05-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='skill_name',
            field=models.CharField(default='General Service', help_text='Specific skill or service offered', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('housekeeping', 'Housekeeping'), ('salon', 'Salon & Beauty'), ('sales', 'Sales'), ('tutoring', 'Tutoring'), ('repair', 'Repair & Maintenance'), ('fitness', 'Fitness & Wellness'), ('pet_care', 'Pet Care'), ('events', 'Event Planning'), ('delivery', 'Delivery'), ('cooking', 'Cooking'), ('photography', 'Photography'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
