# Generated by Django 4.2.30 on 2026-05-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_remove_product_image_product_main_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
    ]
