# Generated by Django 4.2.30 on 2026-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider'), ('merchant', 'Merchant')], default='customer', max_length=20),
        ),
    ]
