# Generated by Django 4.2.30 on 2026-05-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/portfolio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='marketplace.listing')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
