# Generated by Django 6.0.4 on 2026-05-06 18:45

from django.db import migrations, models
import django.db.models.deletion


def migrate_category_to_fk(apps, schema_editor):
    """
    Migrate Listing.category from CharField to ForeignKey(ServiceCategory).
    Uses raw SQL since the old column still exists in the DB at this point.
    """
    ServiceCategory = apps.get_model('marketplace', 'ServiceCategory')
    Listing = apps.get_model('marketplace', 'Listing')

    # First, ensure ServiceCategory has all the old category names
    old_categories = [
        ('housekeeping', 'Housekeeping'),
        ('salon', 'Salon & Beauty'),
        ('sales', 'Sales'),
        ('tutoring', 'Tutoring'),
        ('repair', 'Repair & Maintenance'),
        ('fitness', 'Fitness & Wellness'),
        ('pet_care', 'Pet Care'),
        ('events', 'Event Planning'),
        ('delivery', 'Delivery'),
        ('cooking', 'Cooking'),
        ('photography', 'Photography'),
        ('other', 'Other'),
    ]

    # Create mapping from old code to ServiceCategory
    cat_map = {}
    for code, name in old_categories:
        cat, created = ServiceCategory.objects.get_or_create(name=name)
        cat_map[code] = cat

    # Now update each Listing's category_id field
    # The old 'category' column (CharField) still exists in the DB
    from django.db import connection

    with connection.cursor() as cursor:
        # Get all listings with their old category values
        cursor.execute("SELECT id, category FROM marketplace_listing")
        rows = cursor.fetchall()

        for listing_id, old_category in rows:
            if old_category in cat_map:
                cursor.execute(
                    "UPDATE marketplace_listing SET category_id = %s WHERE id = %s",
                    [cat_map[old_category].id, listing_id]
                )


def reverse_migrate(apps, schema_editor):
    """Reverse migration - clear FK values"""
    Listing = apps.get_model('marketplace', 'Listing')
    Listing.objects.all().update(category_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_create_servicecategory'),
    ]

    operations = [
        # Step 1: Add the new FK column (nullable)
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='listings',
                to='marketplace.servicecategory',
            ),
        ),
        # Step 2: Populate the FK from the old column
        migrations.RunPython(migrate_category_to_fk, reverse_migrate),
        # Step 3: Drop the old 'category' CharField column
        migrations.RunSQL(
            sql="ALTER TABLE marketplace_listing DROP COLUMN category;",
            reverse_sql="ALTER TABLE marketplace_listing ADD COLUMN category VARCHAR(50) DEFAULT 'other';",
        ),
    ]
