# Generated by Django 6.0.4 on 2026-05-06 19:00

from django.db import migrations, models
import django.db.models.deletion


def set_default_category(apps, schema_editor):
    """Set NULL category_id values to 'Other' category"""
    ServiceCategory = apps.get_model('marketplace', 'ServiceCategory')
    Listing = apps.get_model('marketplace', 'Listing')

    # Get or create the 'Other' category
    other_cat, created = ServiceCategory.objects.get_or_create(name='Other')

    # Update NULL values
    Listing.objects.filter(category_id__isnull=True).update(category_id=other_cat.id)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_migrate_category_to_fk'),
    ]

    operations = [
        migrations.RunPython(set_default_category, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='listings',
                to='marketplace.servicecategory',
            ),
        ),
    ]
